package br.com.jangada.bd;

// default package
// Generated 11/09/2016 19:21:00 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Administador generated by hbm2java
 */
public class Administrador implements java.io.Serializable {

	private Integer idAdministrador;
	private String email;
	private String loginAdministrador;
	private String senhaAdministrador;
	private Character ativoAdministrador;
	private Set<Logs> logses = new HashSet<Logs>(0);
	private Set<Noticias> noticiases = new HashSet<Noticias>(0);

	public Administrador() {
	}

	public Administrador(String email, String senhaAdministrador) {
		this.email = email;
		this.senhaAdministrador = senhaAdministrador;
	}

	public Administrador(String email, String senhaAdministrador, Character ativoAdministrador, Set<Logs> logses,
			Set<Noticias> noticiases, String loginAdministrador) {
		this.email = email;
		this.senhaAdministrador = senhaAdministrador;
		this.ativoAdministrador = ativoAdministrador;
		this.logses = logses;
		this.noticiases = noticiases;
		this.loginAdministrador = loginAdministrador;
	}

	public Integer getIdAdministrador() {
		return this.idAdministrador;
	}

	public void setIdAdministrador(Integer idAdministrador) {
		this.idAdministrador = idAdministrador;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getSenhaAdministrador() {
		return this.senhaAdministrador;
	}

	public void setSenhaAdministrador(String senhaAdministrador) {
		this.senhaAdministrador = senhaAdministrador;
	}

	public Character getAtivoAdministrador() {
		return this.ativoAdministrador;
	}

	public void setAtivoAdministrador(Character ativoAdministrador) {
		this.ativoAdministrador = ativoAdministrador;
	}

	public Set<Logs> getLogses() {
		return this.logses;
	}

	public void setLogses(Set<Logs> logses) {
		this.logses = logses;
	}

	public Set<Noticias> getNoticiases() {
		return this.noticiases;
	}

	public void setNoticiases(Set<Noticias> noticiases) {
		this.noticiases = noticiases;
	}

	public String getLoginAdministrador() {
		return loginAdministrador;
	}

	public void setLoginAdministrador(String loginAdministrador) {
		this.loginAdministrador = loginAdministrador;
	}

}
