package br.com.jangada.bd;
// default package
// Generated 11/09/2016 19:21:00 by Hibernate Tools 5.1.0.Alpha1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Investimento generated by hbm2java
 */
public class Investimento implements java.io.Serializable {

	private Integer idInvestimento;
	private String descricaoInvestimento;
	private Integer quantidadeInvestimento;
	private BigDecimal valorInvestimento;
	private Character ativoInvestimento;
	private Set<Investidor> investidors = new HashSet<Investidor>(0);

	public Investimento() {
	}

	public Investimento(String descricaoInvestimento) {
		this.descricaoInvestimento = descricaoInvestimento;
	}

	public Investimento(String descricaoInvestimento, Integer quantidadeInvestimento, BigDecimal valorInvestimento,
			Character ativoInvestimento, Set<Investidor> investidors) {
		this.descricaoInvestimento = descricaoInvestimento;
		this.quantidadeInvestimento = quantidadeInvestimento;
		this.valorInvestimento = valorInvestimento;
		this.ativoInvestimento = ativoInvestimento;
		this.investidors = investidors;
	}

	public Integer getIdInvestimento() {
		return this.idInvestimento;
	}

	public void setIdInvestimento(Integer idInvestimento) {
		this.idInvestimento = idInvestimento;
	}

	public String getDescricaoInvestimento() {
		return this.descricaoInvestimento;
	}

	public void setDescricaoInvestimento(String descricaoInvestimento) {
		this.descricaoInvestimento = descricaoInvestimento;
	}

	public Integer getQuantidadeInvestimento() {
		return this.quantidadeInvestimento;
	}

	public void setQuantidadeInvestimento(Integer quantidadeInvestimento) {
		this.quantidadeInvestimento = quantidadeInvestimento;
	}

	public BigDecimal getValorInvestimento() {
		return this.valorInvestimento;
	}

	public void setValorInvestimento(BigDecimal valorInvestimento) {
		this.valorInvestimento = valorInvestimento;
	}

	public Character getAtivoInvestimento() {
		return this.ativoInvestimento;
	}

	public void setAtivoInvestimento(Character ativoInvestimento) {
		this.ativoInvestimento = ativoInvestimento;
	}

	public Set<Investidor> getInvestidors() {
		return this.investidors;
	}

	public void setInvestidors(Set<Investidor> investidors) {
		this.investidors = investidors;
	}

}
