package br.com.jangada.bd;
// default package
// Generated 11/09/2016 19:21:00 by Hibernate Tools 5.1.0.Alpha1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import org.hibernate.annotations.Formula;

/**
 * Investimento generated by hbm2java
 */
public class Investimento implements java.io.Serializable {

	private Integer idInvestimento;
	private String descricaoInvestimento;
	private Integer quantidadeInvestimento;
	private BigDecimal valorInvestimento;
	private Character ativoInvestimento;	
	private Integer qtdDisponivel;
	private Set<Investidor> investimentoInvestidor = new HashSet<Investidor>(0);

	public Investimento() {
	}

	public Investimento(String descricaoInvestimento) {
		this.descricaoInvestimento = descricaoInvestimento;
	}

	public Investimento(String descricaoInvestimento, Integer quantidadeInvestimento, BigDecimal valorInvestimento,
			Character ativoInvestimento, Set<Investidor> investimentoInvestidor) {
		this.descricaoInvestimento = descricaoInvestimento;
		this.quantidadeInvestimento = quantidadeInvestimento;
		this.valorInvestimento = valorInvestimento;
		this.ativoInvestimento = ativoInvestimento;
		this.investimentoInvestidor = investimentoInvestidor;
	}

	public Integer getIdInvestimento() {
		return this.idInvestimento;
	}

	public void setIdInvestimento(Integer idInvestimento) {
		this.idInvestimento = idInvestimento;
	}

	public String getDescricaoInvestimento() {
		return this.descricaoInvestimento;
	}

	public void setDescricaoInvestimento(String descricaoInvestimento) {
		this.descricaoInvestimento = descricaoInvestimento;
	}

	public Integer getQuantidadeInvestimento() {
		return this.quantidadeInvestimento;
	}

	public void setQuantidadeInvestimento(Integer quantidadeInvestimento) {
		this.quantidadeInvestimento = quantidadeInvestimento;
	}

	public BigDecimal getValorInvestimento() {
		return this.valorInvestimento;
	}

	public void setValorInvestimento(BigDecimal valorInvestimento) {
		this.valorInvestimento = valorInvestimento;
	}

	public Character getAtivoInvestimento() {
		return this.ativoInvestimento;
	}

	public void setAtivoInvestimento(Character ativoInvestimento) {
		this.ativoInvestimento = ativoInvestimento;
	}

	public Integer getQtdDisponivel() {
		return qtdDisponivel;
	}

	public void setQtdDisponivel(Integer qtdDisponivel) {
		this.qtdDisponivel = qtdDisponivel;
	}

	public Set<Investidor> getInvestimentoInvestidor() {
		return investimentoInvestidor;
	}

	public void setInvestimentoInvestidor(Set<Investidor> investimentoInvestidor) {
		this.investimentoInvestidor = investimentoInvestidor;
	}

}
