package br.com.jangada.bd;
// default package
// Generated 11/09/2016 19:21:00 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Investidor generated by hbm2java
 */
public class Investidor implements java.io.Serializable {

	private Integer idInvestidor;
	private String nomeInvestidor;
	private String emailInvestidor;
	private String cpfInvestidor;
	private String cnpjInvestidor;
	private String nomeEmpresaInvestidor;
	private String segmentoEmpresaInvestidor;
	private String cepInvestidor;
	private String logradouroInvestidor;
	private String bairroInvestidor;
	private String cidadeInvestidor;
	private String estadoInvestidor;
	private String paisInvestidor;
	private Date nascimentoInvestidor;
	private Character ativoInvestidor;
	private Set<Investimento> investimentos = new HashSet<Investimento>(0);

	public Investidor() {
	}

	public Investidor(String nomeInvestidor, String emailInvestidor, Date nascimentoInvestidor) {
		this.nomeInvestidor = nomeInvestidor;
		this.emailInvestidor = emailInvestidor;
		this.nascimentoInvestidor =  nascimentoInvestidor;
	}

	public Investidor(String nomeInvestidor, String emailInvestidor, String cpfInvestidor, String cnpjInvestidor,
			String nomeEmpresaInvestidor, String segmentoEmpresaInvestidor, String cepInvestidor,
			String logradouroInvestidor, String bairroInvestidor, String cidadeInvestidor, String estadoInvestidor,
			String paisInvestidor, Character ativoInvestidor, Set<Investimento> investimentos, Date nascimentoInvestidor) {
		this.nomeInvestidor = nomeInvestidor;
		this.emailInvestidor = emailInvestidor;
		this.cpfInvestidor = cpfInvestidor;
		this.cnpjInvestidor = cnpjInvestidor;
		this.nomeEmpresaInvestidor = nomeEmpresaInvestidor;
		this.segmentoEmpresaInvestidor = segmentoEmpresaInvestidor;
		this.cepInvestidor = cepInvestidor;
		this.logradouroInvestidor = logradouroInvestidor;
		this.bairroInvestidor = bairroInvestidor;
		this.cidadeInvestidor = cidadeInvestidor;
		this.estadoInvestidor = estadoInvestidor;
		this.paisInvestidor = paisInvestidor;
		this.ativoInvestidor = ativoInvestidor;
		this.investimentos = investimentos;
		this.nascimentoInvestidor = nascimentoInvestidor;
	}

	public Integer getIdInvestidor() {
		return this.idInvestidor;
	}

	public void setIdInvestidor(Integer idInvestidor) {
		this.idInvestidor = idInvestidor;
	}

	public String getNomeInvestidor() {
		return this.nomeInvestidor;
	}

	public void setNomeInvestidor(String nomeInvestidor) {
		this.nomeInvestidor = nomeInvestidor;
	}

	public String getEmailInvestidor() {
		return this.emailInvestidor;
	}

	public void setEmailInvestidor(String emailInvestidor) {
		this.emailInvestidor = emailInvestidor;
	}

	public String getCpfInvestidor() {
		return this.cpfInvestidor;
	}

	public void setCpfInvestidor(String cpfInvestidor) {
		this.cpfInvestidor = cpfInvestidor;
	}

	public String getCnpjInvestidor() {
		return this.cnpjInvestidor;
	}

	public void setCnpjInvestidor(String cnpjInvestidor) {
		this.cnpjInvestidor = cnpjInvestidor;
	}

	public String getNomeEmpresaInvestidor() {
		return this.nomeEmpresaInvestidor;
	}

	public void setNomeEmpresaInvestidor(String nomeEmpresaInvestidor) {
		this.nomeEmpresaInvestidor = nomeEmpresaInvestidor;
	}

	public String getSegmentoEmpresaInvestidor() {
		return this.segmentoEmpresaInvestidor;
	}

	public void setSegmentoEmpresaInvestidor(String segmentoEmpresaInvestidor) {
		this.segmentoEmpresaInvestidor = segmentoEmpresaInvestidor;
	}

	public String getCepInvestidor() {
		return this.cepInvestidor;
	}

	public void setCepInvestidor(String cepInvestidor) {
		this.cepInvestidor = cepInvestidor;
	}

	public String getLogradouroInvestidor() {
		return this.logradouroInvestidor;
	}

	public void setLogradouroInvestidor(String logradouroInvestidor) {
		this.logradouroInvestidor = logradouroInvestidor;
	}

	public String getBairroInvestidor() {
		return this.bairroInvestidor;
	}

	public void setBairroInvestidor(String bairroInvestidor) {
		this.bairroInvestidor = bairroInvestidor;
	}

	public String getCidadeInvestidor() {
		return this.cidadeInvestidor;
	}

	public void setCidadeInvestidor(String cidadeInvestidor) {
		this.cidadeInvestidor = cidadeInvestidor;
	}

	public String getEstadoInvestidor() {
		return this.estadoInvestidor;
	}

	public void setEstadoInvestidor(String estadoInvestidor) {
		this.estadoInvestidor = estadoInvestidor;
	}

	public String getPaisInvestidor() {
		return this.paisInvestidor;
	}

	public void setPaisInvestidor(String paisInvestidor) {
		this.paisInvestidor = paisInvestidor;
	}

	public Character getAtivoInvestidor() {
		return this.ativoInvestidor;
	}

	public void setAtivoInvestidor(Character ativoInvestidor) {
		this.ativoInvestidor = ativoInvestidor;
	}

	public Set<Investimento> getInvestimentos() {
		return this.investimentos;
	}

	public void setInvestimentos(Set<Investimento> investimentos) {
		this.investimentos = investimentos;
	}

	public Date getNascimentoInvestidor() {
		return nascimentoInvestidor;
	}

	public void setNascimentoInvestidor(Date nascimentoInvestidor) {
		this.nascimentoInvestidor = nascimentoInvestidor;
	}

}
