package br.com.jangada.bd;
// default package
// Generated 11/09/2016 19:21:00 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

/**
 * Logs generated by hbm2java
 */
public class Logs implements java.io.Serializable {

	private Integer idLogs;
	private Administrador administador;
	private String acaoLogs;
	private String tabelaLogs;
	private int registroLogs;
	private Date dataHoraLogs;

	public Logs() {
	}

	public Logs(Administrador administador, String acaoLogs, String tabelaLogs, int registroLogs, Date dataHoraLogs) {
		this.administador = administador;
		this.acaoLogs = acaoLogs;
		this.tabelaLogs = tabelaLogs;
		this.registroLogs = registroLogs;
		this.dataHoraLogs = dataHoraLogs;
	}

	public Integer getIdLogs() {
		return this.idLogs;
	}

	public void setIdLogs(Integer idLogs) {
		this.idLogs = idLogs;
	}

	public Administrador getAdministador() {
		return this.administador;
	}

	public void setAdministador(Administrador administador) {
		this.administador = administador;
	}

	public String getAcaoLogs() {
		return this.acaoLogs;
	}

	public void setAcaoLogs(String acaoLogs) {
		this.acaoLogs = acaoLogs;
	}

	public String getTabelaLogs() {
		return this.tabelaLogs;
	}

	public void setTabelaLogs(String tabelaLogs) {
		this.tabelaLogs = tabelaLogs;
	}

	public int getRegistroLogs() {
		return this.registroLogs;
	}

	public void setRegistroLogs(int registroLogs) {
		this.registroLogs = registroLogs;
	}

	public Date getDataHoraLogs() {
		return this.dataHoraLogs;
	}

	public void setDataHoraLogs(Date dataHoraLogs) {
		this.dataHoraLogs = dataHoraLogs;
	}

}
