package br.com.jangada.bd;
// default package
// Generated 11/09/2016 19:21:00 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

/**
 * Noticias generated by hbm2java
 */
public class Noticias implements java.io.Serializable {

	private Integer idNoticias;
	private Administador administador;
	private String tituloNoticia;
	private String subtituloNoticia;
	private byte[] conteudoNoticia;
	private String urlImagem;
	private Date dataHoraNoticia;
	private Character ativoNoticia;

	public Noticias() {
	}

	public Noticias(String tituloNoticia, String subtituloNoticia) {
		this.tituloNoticia = tituloNoticia;
		this.subtituloNoticia = subtituloNoticia;
	}

	public Noticias(Administador administador, String tituloNoticia, String subtituloNoticia, byte[] conteudoNoticia,
			String urlImagem, Date dataHoraNoticia, Character ativoNoticia) {
		this.administador = administador;
		this.tituloNoticia = tituloNoticia;
		this.subtituloNoticia = subtituloNoticia;
		this.conteudoNoticia = conteudoNoticia;
		this.urlImagem = urlImagem;
		this.dataHoraNoticia = dataHoraNoticia;
		this.ativoNoticia = ativoNoticia;
	}

	public Integer getIdNoticias() {
		return this.idNoticias;
	}

	public void setIdNoticias(Integer idNoticias) {
		this.idNoticias = idNoticias;
	}

	public Administador getAdministador() {
		return this.administador;
	}

	public void setAdministador(Administador administador) {
		this.administador = administador;
	}

	public String getTituloNoticia() {
		return this.tituloNoticia;
	}

	public void setTituloNoticia(String tituloNoticia) {
		this.tituloNoticia = tituloNoticia;
	}

	public String getSubtituloNoticia() {
		return this.subtituloNoticia;
	}

	public void setSubtituloNoticia(String subtituloNoticia) {
		this.subtituloNoticia = subtituloNoticia;
	}

	public byte[] getConteudoNoticia() {
		return this.conteudoNoticia;
	}

	public void setConteudoNoticia(byte[] conteudoNoticia) {
		this.conteudoNoticia = conteudoNoticia;
	}

	public String getUrlImagem() {
		return this.urlImagem;
	}

	public void setUrlImagem(String urlImagem) {
		this.urlImagem = urlImagem;
	}

	public Date getDataHoraNoticia() {
		return this.dataHoraNoticia;
	}

	public void setDataHoraNoticia(Date dataHoraNoticia) {
		this.dataHoraNoticia = dataHoraNoticia;
	}

	public Character getAtivoNoticia() {
		return this.ativoNoticia;
	}

	public void setAtivoNoticia(Character ativoNoticia) {
		this.ativoNoticia = ativoNoticia;
	}

}
